// 后台二级导航和跳转都依赖这组常量，集中维护可以避免运营区和审核区路径漂移。
export const ADMIN_ROUTE_PATHS = {
  overview: "/admin/overview",
  search: "/admin/search",
  moderation: "/admin/moderation",
  moderationArticles: "/admin/moderation/articles",
  moderationMoments: "/admin/moderation/moments",
  moderationComments: "/admin/moderation/comments",
  moderationReports: "/admin/moderation/reports",
  moderationBrandApplications: "/admin/moderation/brand-applications",
  moderationAircraftSubmissions: "/admin/moderation/aircraft-submissions",
  moderationRankings: "/admin/moderation/rankings",
  moderationRatingTargets: "/admin/moderation/rating-targets",
  operations: "/admin/operations",
  operationsArticles: "/admin/operations/articles",
  operationsAircraft: "/admin/operations/aircraft",
  operationsRankings: "/admin/operations/rankings",
  management: "/admin/management",
  managementBrands: "/admin/management/brands",
  managementModels: "/admin/management/models",
  managementCategories: "/admin/management/categories",
  managementContentCategories: "/admin/management/content-categories",
  managementSecurity: "/admin/management/security",
  officialArticles: "/admin/official-articles",
  aircraftSubmissions: "/admin/aircraft-submissions"
} as const;
